server:
    port: 8888
spring:
    cloud:
        config:
            server:
                native:
                    search-locations:
                      - "file:///C:/configurazioni"
    profiles:
        active: native